# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=35)),
                ('country', models.CharField(db_index=True, max_length=250)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
